version: '3.8'

services:

  postgres:
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@company.com
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - ./docker/pgadmin4/data:/var/lib/pgadmin
      - ./docker/pgadmin4/servers.json:/pgadmin4/servers.json
    depends_on:
      postgres:
        condition: service_healthy
